name: todo_withbloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.5.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  toastification: ^3.0.3
  go_router: ^17.0.1
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  equatable: ^2.0.8
  sqflite: ^2.4.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.13
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  analyzer: ^6.4.1
  lottie: ^3.3.2
  loading_animation_widget: ^1.3.0
  flutter_card_swiper: ^7.2.0
  animate_gradient: ^0.0.4
  blur: ^4.0.2
  mesh_gradient: ^1.3.8
  local_auth: ^3.0.0
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/files/
    - assets/audios/



  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/sf-pro-text-regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600